# Generated by Django 2.1 on 2018-08-04 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClpUsdRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('usd', models.DecimalField(decimal_places=4, max_digits=10)),
                ('clp', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
