# Generated by Django 2.1 on 2018-08-04 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convclpusd', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clpusdrate',
            old_name='clp',
            new_name='clp_rate',
        ),
        migrations.RenameField(
            model_name='clpusdrate',
            old_name='usd',
            new_name='usd_rate',
        ),
    ]
