# Generated by Django 2.1 on 2018-08-04 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convclpusd', '0002_auto_20180804_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clpusdrate',
            name='clp_rate',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='clpusdrate',
            name='usd_rate',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
    ]
